import {env} from 'cloudflare:workers';
import {getChatGPTUser} from '../../chatgpt-auth';
import {Repository,HttpError,uid,iso,json} from '@/lib/repository';
import {readLimited} from '@/lib/research';
export const dynamic='force-dynamic';
async function context(){const identity=await getChatGPTUser();if(!identity)throw new HttpError(401,'Anmeldung erforderlich.');const e=env as unknown as {DB:D1Database;BUCKET:R2Bucket};const repo=new Repository(e.DB,e.BUCKET),user=await repo.identify({id:identity.userId,email:identity.email,name:identity.displayName});return {repo,user};}
function fail(e:unknown){return Response.json({error:e instanceof HttpError?e.message:'Datei nicht verfügbar.'},{status:e instanceof HttpError?e.status:500,headers:{'Cache-Control':'no-store'}});}
export async function GET(req:Request){try{const {repo,user}=await context(),q=new URL(req.url).searchParams;let key:string,filename:string,type='application/octet-stream';if(q.get('versionId')){const r=await repo.one('SELECT data FROM versions WHERE id=?',q.get('versionId'));if(!r)throw new HttpError(404,'Dokument fehlt.');const d=JSON.parse(r.data);if(!d.originalKey)return new Response(d.text,{headers:{'Content-Type':'text/plain; charset=utf-8','Cache-Control':'no-store','Content-Disposition':'attachment; filename="rechercheauszug.txt"'}});key=d.originalKey;filename='original-'+d.versionId+(d.pageData.length||d.quality==='ocr_pending'?'.pdf':'.txt');}else{const r=await repo.one('SELECT * FROM uploads WHERE id=? AND owner_id=?',q.get('id'),user.id);if(!r)throw new HttpError(404,'Datei nicht gefunden.');await repo.project(r.project_id,user);key=r.object_key;filename=JSON.parse(r.data).filename;}
 const file=await repo.bucket.get(key);if(!file)throw new HttpError(404,'Datei nicht verfügbar.');return new Response(file.body,{headers:{'Content-Type':type,'Content-Disposition':`attachment; filename="${filename.replace(/[^a-zA-Z0-9._-]/g,'_')}"`,'Cache-Control':'no-store','Content-Security-Policy':"sandbox; default-src 'none'",'X-Content-Type-Options':'nosniff'}});
 }catch(e){return fail(e);}}
export async function POST(req:Request){try{const origin=req.headers.get('origin');if(origin&&origin!==new URL(req.url).origin)throw new HttpError(403,'Ungültiger Ursprung.');const {repo,user}=await context();if(Number(req.headers.get('content-length')??0)>8_100_000)throw new HttpError(413,'Maximal 8 MB je Datei.');const bounded=await readLimited(req as unknown as Response,8_100_000);const form=await new Response(bounded,{headers:{'Content-Type':req.headers.get('content-type')??''}}).formData(),projectId=String(form.get('projectId')??'');await repo.project(projectId,user);const file=form.get('file');if(!(file instanceof File)||file.size>8_000_000)throw new HttpError(413,'Eine Datei bis 8 MB wird benötigt.');if(!['application/pdf','text/plain'].includes(file.type))throw new HttpError(415,'Bitte PDF oder TXT hochladen.');const bytes=await file.arrayBuffer();if(file.type==='application/pdf'&&new TextDecoder().decode(bytes.slice(0,4))!=='%PDF')throw new HttpError(415,'Datei ist kein PDF.');const id=uid(),objectKey=`projects/${user.id}/${projectId}/${id}`;await repo.bucket.put(objectKey,bytes);await repo.exec('INSERT INTO uploads(id,project_id,owner_id,object_key,data) VALUES(?,?,?,?,?)',id,projectId,user.id,objectKey,json({filename:file.name,type:file.type,size:file.size,status:'Quelle nicht prüfbar',uploadedAt:iso(),note:'Nur im eigenen Projekt. Kein automatischer Import in Programmregeln oder Chat.'}));return Response.json({id,status:'geschützt gespeichert; inhaltliche Prüfung offen'},{headers:{'Cache-Control':'no-store'}});
 }catch(e){return fail(e);}}
