import { z } from 'zod';
export const VERSION='1.0.0';
export const REGIONS=['Bund','EU','Baden-Württemberg','Bayern','Berlin','Brandenburg','Bremen','Hamburg','Hessen','Mecklenburg-Vorpommern','Niedersachsen','Nordrhein-Westfalen','Rheinland-Pfalz','Saarland','Sachsen','Sachsen-Anhalt','Schleswig-Holstein','Thüringen'];
export const THEMES=['Energetische Sanierung','Klimaschutz','Klimaanpassung','Erneuerbare Energien'];
export const INSTRUMENTS=['Zuschuss','Förderdarlehen','Zinszuschuss','Tilgungszuschuss','Bürgschaft'];
export const LEGAL_FORMS=['Stadt','Gemeinde','Landkreis','Kommunales Unternehmen','Eigenbetrieb','Zweckverband','Kooperation'];
export const FIELDS:Record<string,{label:string;critical:boolean;volatile?:boolean}>={name:{label:'Vollständiger Name',critical:false},short_name:{label:'Kurzbezeichnung',critical:false},funder:{label:'Fördergeber',critical:false},agency:{label:'Bewilligungsstelle',critical:false},summary:{label:'Kurzbeschreibung',critical:false},region:{label:'Fördergebiet & Einschränkungen',critical:true},applicants:{label:'Antragsberechtigung',critical:true},excluded_applicants:{label:'Ausgeschlossene Antragsteller',critical:true},measures:{label:'Förderfähige Maßnahmen & Nutzungen',critical:true},exclusions:{label:'Ausgeschlossene Maßnahmen',critical:true},instrument:{label:'Förderinstrument',critical:true},amount:{label:'Förderhöhe & Voraussetzungen',critical:true,volatile:true},basis:{label:'Bezugsgröße & Umsatzsteuer',critical:true},costs:{label:'Förderfähige / ausgeschlossene Kosten',critical:true},financing:{label:'Eigenanteil & Kofinanzierung',critical:true},loan:{label:'Darlehensbedingungen & Konditionsstand',critical:true,volatile:true},validity:{label:'Richtliniengültigkeit',critical:true},deadline:{label:'Antragsfenster & Fristen',critical:true,volatile:true},access:{label:'Aktueller Antragszugang',critical:true,volatile:true},funds:{label:'Mittelverfügbarkeit',critical:true,volatile:true},procedure:{label:'Antragsweg, Stufen & Auswahl',critical:true},documents:{label:'Erforderliche Unterlagen & Schwellenwerte',critical:true},start:{label:'Vorhabenbeginn & Ausnahmen',critical:true},bundling:{label:'Bündelung von Gebäuden / Maßnahmen',critical:true},combination:{label:'Kumulierungsregeln',critical:true},obligations:{label:'Technische & weitere Pflichten',critical:true}};
export const INFORMATION=['Belegt','Nicht gefunden','Mehrdeutig','Widersprüchlich','Quelle nicht prüfbar','Projektangabe fehlt','Nicht anwendbar'] as const;
export const FRESHNESS=['aktuell geprüft','erneut zu prüfen','veraltet'] as const;
export const APPROVAL=['Entwurf','automatisch geprüft','fachlich freigegeben'] as const;
export const defaultConfig={language:'Deutsch',timezone:'Europe/Berlin',hour:7,minute:0,strict:true,regions:REGIONS,themes:THEMES,instruments:INSTRUMENTS,volatileHours:24,stableHours:720,maxSources:30,maxSearches:18,maxResults:5,maxBytes:8_000_000,maxAttempts:3,maxRunMinutes:25,maxModelCalls:10,maxDailyEuro:3,searchEuroPerCall:0.01,modelEuroPerCall:0.1,notifications:'in_app',scheduleEnabled:false};
export const scopeSchema=z.object({programId:z.string().min(1),moduleId:z.string().nullable(),callId:z.string().nullable(),variantId:z.string().nullable(),region:z.string().nullable(),applicant:z.string().nullable(),validFrom:z.string().nullable(),validTo:z.string().nullable(),caseId:z.string().nullable()}).strict();
export const evidenceSchema=z.object({id:z.string(),documentId:z.string(),versionId:z.string(),url:z.string().url(),title:z.string().min(1),publisher:z.string().min(1),locator:z.string().min(1),quote:z.string().min(1).max(3000),context:z.string().min(1),checkedAt:z.string().datetime(),pageIndex:z.number().int().nonnegative().nullable(),printedPage:z.string().nullable()}).strict();
export const claimSchema=z.object({id:z.string(),key:z.string().refine(k=>!!FIELDS[k]),value:z.union([z.string(),z.number(),z.boolean()]).nullable(),unit:z.string().nullable(),basis:z.string().nullable(),conditions:z.array(z.string()),scope:scopeSchema,information:z.enum(INFORMATION),freshness:z.enum(FRESHNESS),approval:z.enum(APPROVAL),evidence:z.array(evidenceSchema),checkedAt:z.string().nullable(),reason:z.string(),requiredProjectFields:z.array(z.string()),revision:z.number().int().positive(),supersedes:z.string().nullable()}).strict();
export type Claim=z.infer<typeof claimSchema>;
export type Scope=z.infer<typeof scopeSchema>;
export type Evidence=z.infer<typeof evidenceSchema>;
export type Doc={id:string;sourceId:string;programId:string;versionId:string;title:string;publisher:string;url:string;retrievedAt:string;publishedAt:string|null;versionLabel:string|null;validFrom:string|null;validTo:string|null;hash:string;text:string;quality:'reliable'|'partial'|'ambiguous'|'ocr_pending';originalKey:string|null;pageData:any[];scope:Scope;current:boolean;lastAttempt:string|null;lastSuccess:string|null;reviewedAt:string|null;method:string;references:string[];sourceError?:string|null};
export type Program={id:string;name:string;shortName:string;region:string;themes:string[];instrument:string|null;discoveryNote:string;createdAt:string;revision:number};
export type Question={id:string;programId:string;claimIds:string[];question:string;reason:string;impact:string;documents:string[];nextStep:string;kind:'Nachrecherche'|'Nutzerangabe'|'Fachprüfung'|'Förderstelle';status:string;createdAt:string};
export type Role='admin'|'researcher'|'reviewer'|'reader';
export type User={id:string;email:string;name:string;role:Role};
export function blankScope(programId:string):Scope{return {programId,moduleId:null,callId:null,variantId:null,region:null,applicant:null,validFrom:null,validTo:null,caseId:null};}
export function unknownClaim(programId:string,key:string,reason='Für dieses Feld liegt noch keine vollständig geprüfte Aussage vor.'):Claim{return {id:`${programId}-${key}-empty`,key,value:null,unit:null,basis:null,conditions:[],scope:blankScope(programId),information:'Quelle nicht prüfbar',freshness:'erneut zu prüfen',approval:'Entwurf',evidence:[],checkedAt:null,reason,requiredProjectFields:[],revision:1,supersedes:null};}
