import {z} from 'zod';
import {Repository,HttpError,iso,json} from './repository';
import type {User} from './model';
import type {RuntimeSecrets} from './research';
const keySchema=z.string().trim().min(20).max(1024).regex(/^[\x21-\x7e]+$/);
export const providerInput=z.object({openaiKey:keySchema.optional(),braveKey:keySchema.optional(),model:z.string().trim().min(1).max(100).regex(/^[a-zA-Z0-9_.:-]+$/).optional(),storageRights:z.boolean().optional()}).strict().refine(x=>!!x.openaiKey||!!x.braveKey||!!x.model||x.storageRights!==undefined,'Keine Änderung angegeben.');
const bytes=(s:string)=>Uint8Array.from(atob(s),c=>c.charCodeAt(0));
const encoded=(b:Uint8Array)=>btoa(String.fromCharCode(...b));
async function cryptoKey(master:string|undefined){if(!master)throw new HttpError(503,'Geschützte Schlüsseleingabe noch nicht eingerichtet.');let raw:Uint8Array;try{raw=bytes(master);}catch{throw new HttpError(503,'Schlüsselspeicher nicht verfügbar.');}if(raw.length!==32)throw new HttpError(503,'Schlüsselspeicher nicht verfügbar.');return crypto.subtle.importKey('raw',raw as BufferSource,'AES-GCM',false,['encrypt','decrypt']);}
export async function seal(value:string,master:string|undefined,slot:string){const iv=crypto.getRandomValues(new Uint8Array(12));const ciphertext=await crypto.subtle.encrypt({name:'AES-GCM',iv,additionalData:new TextEncoder().encode(slot)},await cryptoKey(master),new TextEncoder().encode(value));return {v:1,iv:encoded(iv),ciphertext:encoded(new Uint8Array(ciphertext))};}
export async function unseal(value:any,master:string|undefined,slot:string){if(value.v!==1)throw new HttpError(503,'Unbekannte Schlüsselspeicherversion.');try{return new TextDecoder().decode(await crypto.subtle.decrypt({name:'AES-GCM',iv:bytes(value.iv),additionalData:new TextEncoder().encode(slot)},await cryptoKey(master),bytes(value.ciphertext)));}catch{throw new HttpError(503,'Gespeicherter API-Schlüssel kann nicht entschlüsselt werden. Administrator muss ihn erneut hinterlegen.');}}
export async function saveProviders(repo:Repository,u:User,input:unknown,master:string|undefined){repo.require(u,'admin');const parsed=providerInput.parse(input);await cryptoKey(master);const statements:D1PreparedStatement[]=[];const changed:string[]=[];
 for(const [field,slot] of [['openaiKey','OPENAI_API_KEY'],['braveKey','BRAVE_SEARCH_API_KEY']] as const){const value=parsed[field];if(value){const envelope=await seal(value,master,slot);statements.push(repo.db.prepare('INSERT INTO settings(key,data) VALUES(?,?) ON CONFLICT(key) DO UPDATE SET data=excluded.data').bind('provider-secret:'+slot,json(envelope)));changed.push(slot);}}
 const previous=await repo.setting('provider-options',{});const options={...previous,...(parsed.model?{OPENAI_MODEL:parsed.model}:{}),...(parsed.storageRights!==undefined?{BRAVE_STORAGE_RIGHTS:String(parsed.storageRights)}:{})};statements.push(repo.db.prepare('INSERT INTO settings(key,data) VALUES(?,?) ON CONFLICT(key) DO UPDATE SET data=excluded.data').bind('provider-options',json(options)));
 await repo.db.batch(statements);await repo.event('Anbieterzugang aktualisiert',null,{actor:u.id,at:iso(),changed,model:options.OPENAI_MODEL??null,note:'Schlüssel verschlüsselt gespeichert; Anbieterzugriff noch nicht getestet.'});return {saved:true,note:'Verschlüsselt gespeichert. Ein erfolgreicher Anbieterzugriff ist damit noch nicht nachgewiesen.'};}
export async function providerSecrets(repo:Repository,env:RuntimeSecrets&{PROVIDER_VAULT_KEY?:string}){const out={...env,...await repo.setting('provider-options',{})};for(const slot of ['OPENAI_API_KEY','BRAVE_SEARCH_API_KEY'] as const){const stored=await repo.setting('provider-secret:'+slot);if(stored)out[slot]=await unseal(stored,env.PROVIDER_VAULT_KEY,slot);}return out;}
