import {Repository,iso,uid,json,HttpError} from './repository';
import {REGIONS,THEMES,blankScope,unknownClaim,FIELDS,type Doc,type User} from './model';
import {safeTarget,normalize,berlinParts,scheduleDue} from './controls';
import {EXTRACTION_PROMPT,PROMPT_VERSION} from './prompts';
export type RuntimeSecrets={BRAVE_SEARCH_API_KEY?:string;BRAVE_STORAGE_RIGHTS?:string;OPENAI_API_KEY?:string;OPENAI_MODEL?:string;RUNNER_TOKEN?:string;PDF_SERVICE_URL?:string;PDF_SERVICE_TOKEN?:string};
export function queriesFor(region:string,theme:string){const synonyms:Record<string,string[]>={'Energetische Sanierung':['Gebäudehülle Wärmeversorgung Energieeffizienz','Sanierung Nichtwohngebäude Beratung Planung'],'Klimaschutz':['Klimaschutz Konzepte Energieberatung','Treibhausgas kommunale Infrastruktur'],'Klimaanpassung':['Hitze Starkregen Entsiegelung','Klimaanpassung wassersensible Stadtentwicklung'],'Erneuerbare Energien':['Photovoltaik Speicher Solarenergie','erneuerbare Wärme Wärmenetze']};return synonyms[theme].map(s=>`${region} Förderung Förderaufruf Zuschuss Darlehen ${s}`);}
export async function enqueueRun(repo:Repository,automatic=false){
 const config=await repo.config(),at=iso(),day=berlinParts(new Date()).day;
 if(automatic&&!config.scheduleEnabled)return {skipped:true,reason:'Zeitplan deaktiviert'};
 if(automatic){const existing=await repo.one('SELECT id FROM runs WHERE day_key=?',day);if(existing)return {id:existing.id,reused:true};}
 const active=await repo.one("SELECT id FROM runs WHERE status IN ('geplant','läuft') LIMIT 1");if(active)return {id:active.id,reused:true};
 const id=uid();const sources=(await repo.rows('SELECT * FROM sources')).filter(s=>JSON.parse(s.data).enabled);
 const allQueries=config.regions.flatMap((region:string)=>config.themes.flatMap((theme:string)=>queriesFor(region,theme).map(query=>({region,theme,query}))));
 const dayNumber=Math.floor(Date.now()/86400000);const offset=(dayNumber*config.maxSearches)%allQueries.length;
 const rotated=[...allQueries.slice(offset),...allQueries.slice(0,offset)];const planned=rotated.slice(0,config.maxSearches);
 const budgetedSources=sources.slice(0,config.maxSources);
 const info={trigger:automatic?'Zeitplan':'Manuell',plannedSources:budgetedSources.length,totalKnownSources:sources.length,plannedSearches:planned.length,totalGridCells:allQueries.length,skippedSources:sources.length-budgetedSources.length,queryBudget:config.maxSearches,successfulFetches:0,successfulChecks:0,failedSources:0,coverageNote:'Nur protokollierte Quellen und Suchen wurden geprüft. Keine Vollständigkeitsbehauptung.'};
 const plan={sources:budgetedSources.map(s=>({id:uid(),sourceId:s.id})),queries:rotated.map(q=>({...q,id:uid(),selected:planned.includes(q),jobId:uid()}))};
 await repo.exec('INSERT INTO runs(id,day_key,started_at,status,data) VALUES(?,?,?,?,?)',id,automatic?day:null,at,'geplant',json({...info,plan}));
 await completePlan(repo,id,at,plan);return {id,...info};
}
async function completePlan(repo:Repository,id:string,at:string,plan:any){
 const stm:D1PreparedStatement[]=[];
 for(const s of plan.sources)stm.push(repo.db.prepare('INSERT OR IGNORE INTO jobs(id,run_id,kind,status,available_at,data) VALUES(?,?,?,?,?,?)').bind(s.id,id,'fetch','queued',at,json({sourceId:s.sourceId})));
 for(const q of plan.queries){stm.push(repo.db.prepare('INSERT OR IGNORE INTO searches(id,run_id,region,theme,query,status,data) VALUES(?,?,?,?,?,?,?)').bind(q.id,id,q.region,q.theme,q.query,q.selected?'geplant':'Budgetlücke',json({provider:null,results:0})));if(q.selected)stm.push(repo.db.prepare('INSERT OR IGNORE INTO jobs(id,run_id,kind,status,available_at,data) VALUES(?,?,?,?,?,?)').bind(q.jobId,id,'search','queued',at,json({region:q.region,theme:q.theme,query:q.query,searchId:q.id})));}
 for(let i=0;i<stm.length;i+=75)await repo.db.batch(stm.slice(i,i+75));await repo.exec('UPDATE runs SET status=? WHERE id=?','läuft',id);
}

export async function readLimited(response:Response,limit:number){if(Number(response.headers.get('content-length')??0)>limit)throw Error('Dokument überschreitet das Abrufbudget.');const reader=response.body?.getReader();if(!reader)throw Error('Leere Antwort.');let total=0;const parts:Uint8Array[]=[];while(true){const {value,done}=await reader.read();if(done)break;total+=value.length;if(total>limit){await reader.cancel();throw Error('Dokument überschreitet das Abrufbudget.');}parts.push(value);}const out=new Uint8Array(total);let pos=0;for(const p of parts){out.set(p,pos);pos+=p.length;}return out;}
async function limitedFetch(url:string,hosts:string[],limit:number){let target=safeTarget(url,hosts);for(let i=0;i<5;i++){const r=await fetch(target,{redirect:'manual',signal:AbortSignal.timeout(18000),headers:{'User-Agent':'KommunalFoerdermonitor/1.0 (official-source research)','Accept':'text/html,application/pdf,text/plain'}});if(r.status>=300&&r.status<400){const location=r.headers.get('location');if(!location)throw Error('Weiterleitung ohne Ziel.');target=safeTarget(new URL(location,target).href,hosts);continue;}if(!r.ok)throw Error(`Originalquelle nicht erreichbar (HTTP ${r.status}).`);return {bytes:await readLimited(r,limit),url:target,type:r.headers.get('content-type')??'',etag:r.headers.get('etag'),modified:r.headers.get('last-modified')};}throw Error('Zu viele Weiterleitungen.');}
export function robotsAllows(text:string,path:string){let applies=false;const rules:{allow:boolean;path:string}[]=[];for(const raw of text.split('\n')){const line=raw.split('#')[0].trim();const i=line.indexOf(':');if(i<0)continue;const key=line.slice(0,i).toLowerCase(),value=line.slice(i+1).trim();if(key==='user-agent')applies=value==='*'||/kommunalfoerdermonitor/i.test(value);else if(applies&&['allow','disallow'].includes(key)&&value){const escaped=value.replace(/[.+?^${}()|[\]\\]/g,'\\$&').replace(/\*/g,'.*').replace(/\\\$$/,'$');if(new RegExp('^'+escaped).test(path))rules.push({allow:key==='allow',path:value});}}rules.sort((a,b)=>b.path.length-a.path.length||Number(b.allow)-Number(a.allow));return rules[0]?.allow??true;}
async function checkRobots(url:string,hosts:string[]){const u=new URL(url);const r=await fetch(safeTarget(u.origin+'/robots.txt',hosts),{redirect:'manual',signal:AbortSignal.timeout(10000)});if(r.status===404)return;if(!r.ok)throw Error('Abrufregeln konnten nicht geprüft werden (robots.txt).');const content=new TextDecoder().decode(await readLimited(r,250000));if(!robotsAllows(content,u.pathname+u.search))throw Error('Automatischer Abruf durch robots.txt eingeschränkt.');}
export function htmlText(raw:string){return raw.replace(/<(script|style|noscript)\b[^>]*>[\s\S]*?<\/\1>/gi,'').replace(/<\/(p|div|h[1-6]|li|tr|section)>/gi,'\n').replace(/<\/(td|th)>/gi,' | ').replace(/<br\s*\/?>/gi,'\n').replace(/<[^>]*>/g,' ').replace(/&nbsp;/g,' ').replace(/&amp;/g,'&').replace(/&lt;/g,'<').replace(/&gt;/g,'>').replace(/&quot;/g,'"').replace(/&#(\d+);/g,(_,n)=>String.fromCodePoint(Number(n))).replace(/[ \t]+/g,' ').replace(/\n\s*\n/g,'\n\n').trim();}
export async function processSource(repo:Repository,sourceId:string,secrets:RuntimeSecrets){
 const s=await repo.one('SELECT * FROM sources WHERE id=?',sourceId);if(!s)throw Error('Quelle fehlt.');const source=JSON.parse(s.data),config=await repo.config();const hosts=[...new Set((await repo.rows('SELECT data,url FROM sources')).filter(s=>JSON.parse(s.data).verified).map(s=>new URL(s.url).hostname))];
 const attempt=iso();await repo.exec('UPDATE sources SET last_attempt=?,error=NULL WHERE id=?',attempt,s.id);
 try{
  await checkRobots(s.url,hosts);const fetched=await limitedFetch(s.url,hosts,config.maxBytes);const hash=Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',fetched.bytes))).map(n=>n.toString(16).padStart(2,'0')).join('');
  const previous=await repo.one('SELECT * FROM versions WHERE source_id=? AND current=1',s.id);await repo.exec('UPDATE sources SET last_fetch=? WHERE id=?',iso(),s.id);
  if(previous&&previous.hash===hash){
   const d:Doc=JSON.parse(previous.data);d.retrievedAt=iso();d.lastAttempt=attempt;
   // An unchanged validated original can refresh existing human-reviewed claims. Merely retrieving unreviewed content cannot.
   if(d.reviewedAt){d.lastSuccess=iso();await repo.exec('UPDATE sources SET last_check=? WHERE id=?',d.lastSuccess,s.id);const cr=await repo.rows('SELECT DISTINCT c.* FROM claims c JOIN evidence e ON e.claim_id=c.id WHERE e.version_id=? AND c.active=1',d.versionId);for(const row of cr){const c=JSON.parse(row.data);if(c.approval==='fachlich freigegeben'){c.checkedAt=d.lastSuccess;c.freshness='aktuell geprüft';await repo.exec('UPDATE claims SET data=? WHERE id=?',json(c),c.id);}}}
   await repo.exec('UPDATE versions SET data=? WHERE id=?',json(d),d.versionId);return {fetched:true,checked:!!d.reviewedAt,changed:false};
  }
  if(!source.programId&&!s.program_id){
   const raw=new TextDecoder().decode(fetched.bytes);await discoverLinks(repo,raw,fetched.url,null,'Offizieller Quelleneinstieg');return {fetched:true,checked:false,changed:false,discovery:true};
  }
  const programId=s.program_id,documentId=previous?.document_id??`doc-${s.id}`,versionId=uid(),objectKey=`originals/${programId}/${hash}`;
  let text='',quality:Doc['quality']='partial',pageData:any[]=[];const pdf=fetched.bytes[0]===37&&fetched.bytes[1]===80&&fetched.bytes[2]===68&&fetched.bytes[3]===70;
  if(pdf){quality='ocr_pending';if(secrets.PDF_SERVICE_URL&&secrets.PDF_SERVICE_TOKEN){const target=new URL(secrets.PDF_SERVICE_URL);if(target.protocol!=='https:')throw Error('PDF-Dienst benötigt HTTPS.');const r=await fetch(target.href,{method:'POST',redirect:'error',signal:AbortSignal.timeout(25000),headers:{Authorization:`Bearer ${secrets.PDF_SERVICE_TOKEN}`,'Content-Type':'application/pdf'},body:fetched.bytes});if(!r.ok)throw Error('PDF-Dienst nicht erreichbar.');const result=JSON.parse(new TextDecoder().decode(await readLimited(r,8_000_000)));if(!Array.isArray(result.pages)||result.pages.length>150)throw Error('Ungültige PDF-Ausgabe.');pageData=result.pages;text=pageData.map(p=>`[PDF-Seitenindex ${p.pageIndex}; gedruckte Seite ${p.printedPage??'unbekannt'}]\n${p.text}`).join('\n\n');quality=result.requiresVisual?'ambiguous':'partial';}}
  else if(/html|text\/plain/.test(fetched.type)){const raw=new TextDecoder().decode(fetched.bytes);text=htmlText(raw);await discoverLinks(repo,raw,fetched.url,programId,'Referenz im Originaldokument');}
  else throw Error('Nicht unterstützter Dokumenttyp; manuelle Prüfung nötig.');
  await repo.bucket.put(objectKey,fetched.bytes,{httpMetadata:{contentType:pdf?'application/pdf':'text/plain'}});
  const d:Doc={id:documentId,sourceId:s.id,programId,versionId,title:source.title??source.type+' · '+source.publisher,publisher:source.publisher,url:fetched.url,retrievedAt:iso(),publishedAt:null,versionLabel:null,validFrom:null,validTo:null,hash,text,quality,originalKey:objectKey,pageData,scope:source.scope??blankScope(programId),current:true,lastAttempt:attempt,lastSuccess:null,reviewedAt:null,method:pdf?'PDF-Dienst / Originaldatei':'HTML-Textauszug mit erhaltenem Rohsnapshot',references:[]};
  const duplicate=await repo.one('SELECT * FROM versions WHERE document_id=? AND hash=?',documentId,hash);
  const stm=[repo.db.prepare('UPDATE versions SET current=0 WHERE source_id=?').bind(s.id),repo.db.prepare('UPDATE sources SET last_check=NULL WHERE id=?').bind(s.id),repo.db.prepare('UPDATE programs SET revision=revision+1 WHERE id=?').bind(programId)];
  if(duplicate){d.versionId=duplicate.id;stm.push(repo.db.prepare('UPDATE versions SET current=1,data=? WHERE id=?').bind(json(d),d.versionId));}else stm.push(repo.db.prepare('INSERT INTO versions(id,document_id,source_id,program_id,hash,current,data) VALUES(?,?,?,?,?,1,?)').bind(versionId,documentId,s.id,programId,hash,json(d)));
  const dependent=await repo.rows('SELECT DISTINCT c.* FROM claims c JOIN evidence e ON e.claim_id=c.id JOIN versions v ON v.id=e.version_id WHERE v.source_id=? AND c.active=1',s.id);
  for(const row of dependent){const c=JSON.parse(row.data);c.freshness='erneut zu prüfen';stm.push(repo.db.prepare('UPDATE claims SET data=? WHERE id=?').bind(json(c),c.id));}
  await repo.db.batch(stm);await repo.event(previous?'Dokument geändert':'Dokument abgerufen',programId,{sourceId:s.id,oldVersion:previous?.id??null,newVersion:d.versionId,semanticChange:null,note:'Fachliche Bedeutung noch nicht festgestellt. Abhängige Aussagen sind gesperrt.'});
  await repo.addQuestion(programId,{question:pdf&&quality==='ocr_pending'?'PDF auslesen und Seiten visuell prüfen':'Neue Dokumentfassung fachlich auswerten',reason:'Ein Abruf ist keine fachliche Prüfung.',documents:[d.versionId],kind:'Fachprüfung',nextStep:'Original öffnen, Aussagen mit Kontext erfassen und relevante Änderungen prüfen.'});return {fetched:true,checked:false,changed:!!previous,versionId:d.versionId};
 }catch(e){await repo.exec('UPDATE sources SET error=? WHERE id=?',e instanceof Error?e.message:'Abruf fehlgeschlagen',s.id);throw e;}
}
async function discoverLinks(repo:Repository,raw:string,base:string,programId:string|null,origin:string){let n=0;for(const m of raw.matchAll(/<a\b[^>]*href=["']([^"']+)["'][^>]*>([\s\S]*?)<\/a>/gi)){const label=htmlText(m[2]);if(!/richtlinie|merkblatt|förder|foerder|faq|antrag|\.pdf|klima|energie/i.test(m[1]+' '+label))continue;let u:URL;try{u=new URL(m[1],base);}catch{continue;}if(u.protocol!=='https:')continue;u.hash='';await repo.exec('INSERT OR IGNORE INTO candidates(id,url,status,data) VALUES(?,?,?,?)',uid(),u.href,'ungeprüft',json({title:label.slice(0,250)||'Verlinkte Quelle',programId,origin,discoveredAt:iso(),note:'Berechtigung und Herausgeber müssen geprüft werden.'}));if(++n>=30)break;}}
export async function extractVersion(repo:Repository,versionId:string,secrets:RuntimeSecrets,u:User){
 if(!secrets.OPENAI_API_KEY||!secrets.OPENAI_MODEL)throw new HttpError(409,'KI-Extraktion ist noch nicht konfiguriert. Aussagen können mit Originalbeleg manuell erfasst werden.');
 const row=await repo.one('SELECT data FROM versions WHERE id=? AND current=1',versionId);if(!row)throw new HttpError(404,'Aktuelle Version fehlt.');const d:Doc=JSON.parse(row.data);if(!d.text||d.quality==='ambiguous'||d.quality==='ocr_pending')throw new HttpError(422,'Dokument zuerst zuverlässig auslesen.');
 if(d.text.length>50000)throw new HttpError(422,'Dokument zu lang für das konfigurierte Kontextbudget. Modulweise fachlich aufteilen; nicht stillschweigend abschneiden.');
 const config=await repo.config();await reserveBudget(repo,'model',config.modelEuroPerCall,config);
 const r=await fetch('https://api.openai.com/v1/chat/completions',{method:'POST',redirect:'error',signal:AbortSignal.timeout(25000),headers:{Authorization:`Bearer ${secrets.OPENAI_API_KEY}`,'Content-Type':'application/json'},body:json({model:secrets.OPENAI_MODEL,store:false,max_completion_tokens:5000,response_format:{type:'json_object'},messages:[{role:'system',content:EXTRACTION_PROMPT+' Erlaubte Schlüssel: '+Object.keys(FIELDS).join(', ')},{role:'user',content:json({scope:d.scope,documentId:d.id,versionId:d.versionId,untrustedDocument:d.text})}]})});
 if(!r.ok)throw Error(`KI-Anbieter meldet HTTP ${r.status}.`);const result=await r.json() as any;let parsed:any;try{parsed=JSON.parse(result.choices?.[0]?.message?.content??'');}catch{throw Error('KI-Ausgabe ist kein gültiges JSON.');}
 if(!Array.isArray(parsed.claims)||parsed.claims.length>15)throw Error('Ungültiges Extraktionsschema.');const saved=[],rejected=[];
 for(const x of parsed.claims){if(x.value===null)continue;try{const c=unknownClaim(d.programId,x.key);Object.assign(c,{value:x.value,unit:x.unit??null,basis:x.basis??null,information:'Belegt',scope:d.scope,conditions:x.conditions,requiredProjectFields:x.requiredProjectFields,evidence:[{id:uid(),documentId:d.id,versionId:d.versionId,url:d.url,title:d.title,publisher:d.publisher,locator:x.locator,quote:x.quote,context:x.context,checkedAt:iso(),pageIndex:null,printedPage:null}],reason:`KI-Vorschlag ${PROMPT_VERSION}; Tragfähigkeit benötigt Fachprüfung.`});saved.push(await repo.propose(c,u));}catch(e){rejected.push(String(e));}}
 await repo.event('Extraktion geprüft',d.programId,{saved:saved.length,rejected,promptVersion:PROMPT_VERSION,usage:result.usage??null});return {saved:saved.length,rejected};
}
async function reserveBudget(repo:Repository,kind:'model'|'search',cost:number,config:any){const day=berlinParts(new Date()).day,key=`budget:${day}`;await repo.exec('INSERT OR IGNORE INTO settings(key,data) VALUES(?,?)',key,json({spent:0,model:0,search:0}));const r=await repo.exec(`UPDATE settings SET data=json_set(data,'$.spent',json_extract(data,'$.spent')+?,'$.${kind}',json_extract(data,'$.${kind}')+1) WHERE key=? AND json_extract(data,'$.spent')+?<=? AND json_extract(data,'$.${kind}')<?`,cost,key,cost,config.maxDailyEuro,kind==='model'?config.maxModelCalls:config.maxSearches);if(!r.meta.changes)throw Error('Konfiguriertes Tagesbudget erreicht.');}
async function searchJob(repo:Repository,data:any,secrets:RuntimeSecrets){
 if(!secrets.BRAVE_SEARCH_API_KEY||secrets.BRAVE_STORAGE_RIGHTS!=='true')throw Error('Websuche nicht konfiguriert: Suchschlüssel und Speicherrechte fehlen.');const config=await repo.config();await reserveBudget(repo,'search',config.searchEuroPerCall,config);const u=new URL('https://api.search.brave.com/res/v1/web/search');u.searchParams.set('q',data.query);u.searchParams.set('count',String(config.maxResults));u.searchParams.set('country','DE');u.searchParams.set('search_lang','de');
 const r=await fetch(u.href,{redirect:'error',signal:AbortSignal.timeout(18000),headers:{'X-Subscription-Token':secrets.BRAVE_SEARCH_API_KEY,'Accept':'application/json'}});if(!r.ok)throw Error(`Suchanbieter meldet HTTP ${r.status}.`);const result=await r.json() as any;const items=(result.web?.results??[]).slice(0,config.maxResults);for(const item of items){try{const url=new URL(item.url);if(url.protocol!=='https:')continue;url.hash='';await repo.exec('INSERT OR IGNORE INTO candidates(id,url,status,data) VALUES(?,?,?,?)',uid(),url.href,'ungeprüft',json({title:String(item.title).slice(0,300),region:data.region,theme:data.theme,query:data.query,origin:'Brave Search; nur Hinweis',discoveredAt:iso(),programId:null}));}catch{continue;}}
 await repo.exec('UPDATE searches SET status=?,at=?,data=? WHERE id=?','durchgeführt',iso(),json({provider:'Brave Search',results:items.length}),data.searchId);return {results:items.length};
}
export async function tick(repo:Repository,secrets:RuntimeSecrets,automatic=false){
 const config=await repo.config();if(automatic){await repo.exec('INSERT INTO settings(key,data) VALUES(?,?) ON CONFLICT(key) DO UPDATE SET data=excluded.data','runner-heartbeat',json({at:iso()}));const last=await repo.one('SELECT day_key FROM runs WHERE day_key IS NOT NULL ORDER BY day_key DESC LIMIT 1');if(scheduleDue(new Date(),last?.day_key??null,config.hour,config.minute))await enqueueRun(repo,true);}
 const at=iso();
 for(const r of await repo.rows("SELECT * FROM runs WHERE status='geplant'")){const info=JSON.parse(r.data);if(info.plan)await completePlan(repo,r.id,r.started_at,info.plan);}
 await repo.exec("UPDATE jobs SET status=CASE WHEN attempts>=? THEN 'failed' ELSE 'queued' END,error='Lease abgelaufen; vorheriger Prozess ausgefallen',lease_token=NULL,lease_until=NULL WHERE status='running' AND lease_until<?",config.maxAttempts,at);
 const cutoff=new Date(Date.now()-config.maxRunMinutes*60000).toISOString();
 await repo.exec("UPDATE jobs SET status='failed',error='Zeitbudget des Laufs überschritten' WHERE status='queued' AND run_id IN(SELECT id FROM runs WHERE started_at<? AND status='läuft')",cutoff);
 const job=await repo.one("SELECT j.* FROM jobs j JOIN runs r ON r.id=j.run_id WHERE j.status='queued' AND j.available_at<=? AND r.status='läuft' ORDER BY j.rowid LIMIT 1",at);if(!job){for(const r of await repo.rows("SELECT * FROM runs WHERE status='läuft'"))await finalizeRun(repo,r);return {idle:true};}
 const token=uid();const lock=await repo.exec("UPDATE jobs SET status='running',attempts=attempts+1,lease_token=?,lease_until=? WHERE id=? AND status='queued'",token,new Date(Date.now()+120000).toISOString(),job.id);if(!lock.meta.changes)return {busy:true};
 const data=JSON.parse(job.data);const run=await repo.one('SELECT * FROM runs WHERE id=?',job.run_id);let result:any;try{
  if(Date.now()-Date.parse(run.started_at)>config.maxRunMinutes*60000)throw Error('Zeitbudget des Laufs überschritten.');
  result=job.kind==='fetch'?await processSource(repo,data.sourceId,secrets):job.kind==='extract'?await extractVersion(repo,data.versionId,secrets,{id:'system:extractor',name:'Rechercheautomation',email:'',role:'researcher'}):await searchJob(repo,data,secrets);
  if(job.kind==='fetch'&&result.versionId)await repo.exec('INSERT OR IGNORE INTO jobs(id,run_id,kind,status,available_at,data) VALUES(?,?,?,?,?,?)',`extract:${result.versionId}`,job.run_id,'extract','queued',iso(),json({versionId:result.versionId}));
  await repo.exec("UPDATE jobs SET status='done',error=NULL,lease_until=NULL,data=? WHERE id=? AND lease_token=?",json({...data,result}),job.id,token);
 }catch(e){const message=e instanceof Error?e.message:'Auftrag fehlgeschlagen';const retry=job.attempts+1<config.maxAttempts&&!/nicht konfiguriert|Budget|budget|robots|Abrufziel/.test(message);await repo.exec('UPDATE jobs SET status=?,error=?,lease_until=NULL,available_at=? WHERE id=? AND lease_token=?',retry?'queued':'failed',message,new Date(Date.now()+Math.min(300,Math.pow(2,job.attempts)*15)*1000).toISOString(),job.id,token);if(job.kind==='search')await repo.exec('UPDATE searches SET status=?,at=?,data=? WHERE id=?',retry?'Wiederholung geplant':'Rechercheausfall',iso(),json({error:message}),data.searchId);result={error:message,retry};}
 const status=await finalizeRun(repo,run);return {runId:job.run_id,status,result};
}
async function finalizeRun(repo:Repository,run:any){
 const jobs=await repo.rows('SELECT kind,status,data FROM jobs WHERE run_id=?',run.id),info=JSON.parse(run.data);info.successfulFetches=jobs.filter(j=>j.kind==='fetch'&&j.status==='done').length;info.successfulChecks=jobs.filter(j=>j.kind==='fetch'&&JSON.parse(j.data).result?.checked).length;info.failedSources=jobs.filter(j=>j.kind==='fetch'&&j.status==='failed').length;info.successfulSearches=jobs.filter(j=>j.kind==='search'&&j.status==='done').length;
 const unfinished=jobs.some(j=>['queued','running'].includes(j.status));const complete=jobs.length>0&&!jobs.some(j=>j.status==='failed')&&!info.skippedSources&&info.successfulChecks===info.plannedSources;const status=unfinished?'läuft':complete?'vollständig im geplanten Umfang geprüft':jobs.some(j=>j.status==='done')?'teilweise erfolgreich':'fehlgeschlagen';await repo.exec('UPDATE runs SET status=?,ended_at=?,data=? WHERE id=?',status,unfinished?null:iso(),json(info),run.id);if(!unfinished&&status!=='vollständig im geplanten Umfang geprüft'&&!run.ended_at)await repo.event('Rechercheausfall',null,{runId:run.id,status,...info,plan:undefined});return status;

}
